#version 450

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0) uniform sampler2D NormalGbuffer;
layout(set = 0, binding = 1) uniform sampler2D DepthGbuffer;
layout(set = 0, binding = 2, r8) writeonly uniform image2D outAO;

layout(std140, set = 1, binding = 0) uniform PerFrameCB
{
    mat4 viewMatrix;
    mat4 projMatrix;
    vec3 cameraPos;
    float pointLightNumber;
    float spotLightNumber;
    DirectionalLightRenderResource directionalLit;
} uboPerFrame;

int main()
{
    ivec2 px = ivec2(gl_GlobalInvocationID.xy);
    vec2 uv = (vec2(px) + 0.5) * invScreenSize;
    float depth = texture(DepthGbuffer, uv).rgb;

    if (depth == FAR) 
    { 
        imageStore(outAO, px, vec4(1.0)); 
        return;
    }


}

